apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: pfe-web-stack
spec:
  schema:
    apiVersion: v1alpha1
    kind: FinWebAppStack
    spec:
      projectName: string
      bucketType:
        type: string
        default: private
    status:
      stackConditions: ${projectns.status.phase}
  # Define your resources
  resources:
    - id: projectns
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.name}
    - id: awss3bucket
      template:
        apiVersion: s3.services.k8s.aws/v1alpha1
        kind: Bucket
        metadata:
          name: ${schema.spec.name}-b
          namespace: ${schema.spec.name}
        spec:
          name: pfe-ue1-${schema.spec.name}-bucket